# Generated by Django 4.2.2 on 2023-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
            ],
        ),
    ]
