# Generated by Django 4.2.2 on 2023-06-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criacao',
            options={'ordering': ['data_entrada']},
        ),
        migrations.AlterField(
            model_name='criacao',
            name='data_entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
    ]
