# Generated by Django 4.2.2 on 2023-06-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0002_alter_criacao_options_alter_criacao_data_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criacao',
            options={'ordering': ['raca']},
        ),
    ]
