# Generated by Django 4.2.2 on 2023-06-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0003_alter_criacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criacao',
            options={'ordering': ['data_entrada']},
        ),
    ]
