# Generated by Django 4.2.2 on 2023-06-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0004_alter_criacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producao.criacao', verbose_name='Criação')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
